### ISSUE TITLE
Install is ko since Install Grafana plugins commit

### ISSUE THREAD

**Issue by CAbdel** [jtyr/ansible-grafana#9]
We use this role in our project.
The execution is KO since your last commit. We've got this error : 

`13:42:16 ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
13:42:16 
13:42:16 The error appears to have been in '.../galaxy_roles/jtyr.grafana/tasks/main.yaml': line 114, column 3, but may
13:42:16 be elsewhere in the file depending on the exact syntax problem.
13:42:16 
13:42:16 The offending line appears to be:
13:42:16 
13:42:16 
13:42:16 - name: Install Grafana plugins
13:42:16   ^ here`

What may be interesting to have is to upgrade the version (with your last commit) so we could use the older one. But as I see, you still use the same version v1.0. Is it correct?

**Comment by jtyr** [comment]
Thanks for reporting this, @CAbdel. The `grafana_plugin` module should be available since Ansible 2.5. What's your Ansible version? I run it on Ansible v2.7.5 and it works just fine.

**Comment by CAbdel** [comment]
@jtyr Thanks for your answer! It worked with ansible v2.5.0.
However I think it could be a good practice to use a new version for your role when you upgrade the ansible version you use in it. So projects that are using the role may point the old version in production env during their upgrade process. Just a suggestion!!

**Comment by jtyr** [comment]
The Ansible version is documented in the [meta](https://github.com/jtyr/ansible-grafana/blob/master/meta/main.yml#L7) file.

**Comment by CAbdel** [comment]
Sure the version is in the meta file (good practice) but my observation is about the upgrade of the branch number when you upgraded the min_ansible_version.

In your last commit you updated the min_ansible_version from 2.1 to 2.5
 - min_ansible_version: 2.1
 + min_ansible_version: 2.5

You may create a tag (or a branch) with "min_ansible_version: 2.1" (and all the related role definition) as V1.0 and your master tag V2.0 for example. This way we could use the jtyr.grafana role with the V1.0 version with no need to upgrade our ansible version.

**Comment by jtyr** [comment]
I got you. I have just created a tag `v0.9` for the old version, if you still interested to use it.

**Comment by CAbdel** [comment]
@jtyr You rock!! 
You finally made us upgrade our ansible version so I won't use the new tag. Maybe usefull for others.
